<?php

namespace ContactListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllAndSortAZ()
    {
        $dql = "SELECT contact FROM ContactListBundle:Contact contact ORDER BY contact.name";

        $contacts = $this->getEntityManager()->createQuery($dql)->getResult();

        return $contacts;
    }

    public function findStartsWidth($data)
    {
        $dql = "SELECT contact FROM ContactListBundle:Contact contact WHERE contact.name LIKE :name";

        $name = '%'.$data.'%';

        $contacts = $this->getEntityManager()->createQuery($dql)->setParameter('name', $name)->getResult();

        return $contacts;
    }

    public function findContactInfo($id)
    {
        $dql = "SELECT c,a,e,p,g FROM ContactListBundle:Contact c 
                LEFT JOIN c.addresses a
                LEFT JOIN c.emails e
                LEFT JOIN c.phonenumbers p
                LEFT JOIN c.groups g
                WHERE c.id=:id";
        return $this->getEntityManager()->createQuery($dql)
            ->setParameter('id', $id)->getOneOrNullResult();
    }
}
