<?php

namespace ContactListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllAndSortAZ()
    {
        $dql = "SELECT contact FROM ContactListBundle:Contact contact ORDER BY contact.name";

        $contacts = $this->getEntityManager()->createQuery($dql)->getResult();

        return $contacts;
    }
}
