<?php

namespace ContactListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneNumberRepository extends EntityRepository
{
    public function findAllById($id)
    {
        $dql = "SELECT phoneNumber FROM ContactListBundle:PhoneNumber phoneNumber WHERE phoneNumber.contact = :id";

        $phoneNumbers = $this->getEntityManager()->createQuery($dql)->setParameter('id', $id)->getResult();

        return $phoneNumbers;
    }
}
